[package]
name = "kchat-drive-store-sqlite"
description = "SQLCipher native persistence for KChat Drive."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
kchat-drive-types = { workspace = true }
kchat-drive-sync-core = { workspace = true }
rusqlite = { workspace = true }
refinery = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
